apiVersion: v1 # Версия API
kind: Pod # Объект, который создаем
metadata:
  name: web # Название Pod
  labels: # Метки в формате key: value
    lesson-number: "1"
spec: # Описание Pod
  volumes:
  - name: app
    emptyDir: {}
  containers: # Описание контейнеров внутри Pod
    - name: web # Название контейнера
      image: pl7ofit/otus_lessons:l1_nginx # Образ из которого создается контейнер
      volumeMounts:
      - name: app
        mountPath: /app
  initContainers:
    - name: init
      image: busybox:1.31.0
      command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      volumeMounts:
      - name: app
        mountPath: /app

